program: wandb_sweep.py
method: grid
metric:
  name: val_loss
  goal: minimize

parameters:
  l1_out_channels:
    values: [1, 3, 5]
  l1_kernel_size:
    values: [9, 31, 75, 149]
  l1_stride:
    values: [5, 15, 25]
  l2_out_channels:
    values: [1, 8, 16]
  l2_kernel_size:
    values: [7, 15, 31]
  l2_stride:
    values: [2, 5, 10]
  l3_out_channels:
    values: [1, 16, 32]
  l3_kernel_size:
    values: [3, 5, 7]
  l3_stride:
    values: [2]
  lr:
    value: 0.001
  batch_size:
    value: 100
  weight_decay:
    value: 0.001
  lr_scheduler_loop:
    value: 7
  epochs:
    value: 3
  use_noise_transform:
    value: true
  noise_level:
    value: 0.1
  data_folder:
    value: ./data/real_512_0_004step_tensor.lmdb
  dataset_train_keys_fname:
    value: 004_dark_train.txt
  dataset_val_keys_fname:
    value: 004_dark_val.txt