_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 24
                - 55
            "4": 3.11.11
            "5": 0.19.7
            "8":
                - 1
                - 2
                - 5
            "12": 0.19.7
            "13": linux-x86_64
batch_size:
    value: 64
epochs:
    value: 50
experiment_name:
    value: fc_4layers
lr:
    value: 0.001
